import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { trpc } from "@/lib/trpc";
import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

type Content = Record<string, any>;
type ImageSlot = "hero" | "specialist" | "gallery-1" | "gallery-2" | "gallery-3";

const mono = { fontFamily: "'Space Mono', monospace" } as const;
const fieldStyle = { ...mono, width: "100%", padding: "0.7rem 0", border: "none", borderBottom: "1px solid oklch(0.82 0.005 60)", background: "transparent", fontSize: "0.78rem", outline: "none" } as const;

function Field({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) {
  return <label style={{ display: "block", marginBottom: "1.2rem" }}><span style={{ ...mono, display: "block", fontSize: "0.58rem", letterSpacing: "0.1em", textTransform: "uppercase", color: "oklch(0.48 0.01 60)", marginBottom: "0.35rem" }}>{label}</span>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} style={{ ...fieldStyle, minHeight: "84px", lineHeight: 1.6, resize: "vertical" }} /> : <input value={value} onChange={(event) => onChange(event.target.value)} style={fieldStyle} />}</label>;
}

function Group({ title, children }: { title: string; children: React.ReactNode }) {
  return <section style={{ marginTop: "3.5rem" }}><h2 style={{ ...mono, fontSize: "0.72rem", letterSpacing: "0.1em", textTransform: "uppercase", paddingBottom: "0.8rem", marginBottom: "1.5rem", borderBottom: "1px solid oklch(0.86 0.005 60)" }}>{title}</h2>{children}</section>;
}

function text(value: unknown) { return typeof value === "string" ? value : ""; }

async function optimiseImage(file: File) {
  const bitmap = await createImageBitmap(file);
  const maxSize = 1800;
  const scale = Math.min(1, maxSize / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement("canvas");
  canvas.width = Math.round(bitmap.width * scale);
  canvas.height = Math.round(bitmap.height * scale);
  const context = canvas.getContext("2d");
  if (!context) throw new Error("No se ha podido preparar la imagen.");
  context.drawImage(bitmap, 0, 0, canvas.width, canvas.height);
  bitmap.close();
  const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((image) => image ? resolve(image) : reject(new Error("No se ha podido optimizar la imagen.")), "image/jpeg", 0.86));
  const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = reject; reader.readAsDataURL(blob); });
  return { base64, mimeType: "image/jpeg", filename: `${file.name.replace(/\.[^.]+$/, "") || "imagen"}.jpg` };
}

function ImageUpload({ label, slot, url, onPersist, onPublished }: { label: string; slot: ImageSlot; url: string; onPersist: (url: string) => Content; onPublished?: (url: string) => void }) {
  const inputRef = useRef<HTMLInputElement>(null);
  const utils = trpc.useUtils();
  const [previewUrl, setPreviewUrl] = useState("");
  const persist = trpc.content.updateBlepharoplasty.useMutation();
  const upload = trpc.assets.upload.useMutation({
    onSuccess: async ({ url: uploadedUrl }) => {
      try { await persist.mutateAsync({ patch: onPersist(uploadedUrl) }); onPublished?.(uploadedUrl); await utils.content.getBlepharoplasty.invalidate(); setPreviewUrl(""); toast.success(`${label}: imagen sustituida y publicada`); }
      catch (error) { toast.error(error instanceof Error ? error.message : "La imagen se ha subido, pero no se ha podido publicar."); }
    },
    onError: (error) => toast.error(error.message),
  });
  const choose = async (file?: File) => {
    if (!file) return;
    if (!file.type.startsWith("image/")) return toast.error("Selecciona un archivo de imagen.");
    if (file.size > 20 * 1024 * 1024) return toast.error("La imagen debe pesar menos de 20 MB.");
    try { setPreviewUrl(URL.createObjectURL(file)); upload.mutate({ slot, ...(await optimiseImage(file)) }); }
    catch (error) { toast.error(error instanceof Error ? error.message : "No se ha podido preparar la imagen."); }
  };
  const busy = upload.isPending || persist.isPending;
  const displayUrl = previewUrl || url;
  return <div style={{ border: "1px solid oklch(0.86 0.005 60)", padding: "0.9rem", background: "white" }}><p style={{ ...mono, fontSize: "0.58rem", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "0.65rem" }}>{label}</p>{displayUrl ? <img src={displayUrl} alt={label} style={{ width: "100%", height: "155px", objectFit: "cover", marginBottom: "0.75rem" }} /> : <div style={{ height: "155px", display: "grid", placeItems: "center", background: "oklch(0.94 0.005 60)", color: "oklch(0.52 0.01 60)", ...mono, fontSize: "0.6rem", marginBottom: "0.75rem" }}>Sin imagen</div>}<input ref={inputRef} type="file" accept="image/*" disabled={busy} style={{ position: "absolute", width: 1, height: 1, opacity: 0, pointerEvents: "none" }} onClick={(event) => { event.currentTarget.value = ""; }} onChange={(event) => choose(event.target.files?.[0])} /><button type="button" disabled={busy} onClick={() => inputRef.current?.click()} style={{ ...mono, display: "block", width: "100%", textAlign: "center", padding: "0.55rem", border: "1px solid oklch(0.2 0.005 60)", background: "white", color: "oklch(0.1 0.005 60)", fontSize: "0.58rem", cursor: busy ? "wait" : "pointer" }}>{busy ? "Subiendo y publicando..." : "Seleccionar y sustituir imagen"}</button></div>;
}

export default function AdminBlepharoplasty() {
  const { user, loading } = useAuth();
  const [previewEditor, setPreviewEditor] = useState(() => Boolean(window.sessionStorage.getItem("blefaroplastia-preview-editor-code")));
  const [accessCode, setAccessCode] = useState("");
  const { data, isLoading } = trpc.content.getBlepharoplasty.useQuery();
  const utils = trpc.useUtils();
  const [content, setContent] = useState<Content | null>(null);
  const saveMutation = trpc.content.updateBlepharoplasty.useMutation({ onSuccess: () => { toast.success("Textos guardados"); utils.content.getBlepharoplasty.invalidate(); }, onError: (error) => toast.error(error.message) });
  useEffect(() => { if (data) setContent(JSON.parse(JSON.stringify(data))); }, [data]);

  const gallery = useMemo(() => Array.isArray(content?.cases?.items) && content.cases.items.length ? content.cases.items : [{ label: "Imagen 01", imageUrl: "", imageAlt: "" }, { label: "Imagen 02", imageUrl: "", imageAlt: "" }, { label: "Imagen 03", imageUrl: "", imageAlt: "" }], [content]);
  const setSection = (section: string, value: any) => setContent((current) => ({ ...(current ?? {}), [section]: value }));
  const setGalleryItem = (index: number, key: string, value: string) => setSection("cases", { ...(content?.cases ?? {}), items: gallery.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, [key]: value } : item) });
  const setCard = (index: number, key: string, value: string) => setSection("problem", { ...(content?.problem ?? {}), cards: (content?.problem?.cards ?? []).map((card: any, cardIndex: number) => cardIndex === index ? { ...card, [key]: value } : card) });
  const setStep = (index: number, key: string, value: string) => setSection("process", { ...(content?.process ?? {}), steps: (content?.process?.steps ?? []).map((step: any, stepIndex: number) => stepIndex === index ? { ...step, [key]: value } : step) });
  const save = () => { if (!content) return; const { _id, _type, _rev, _createdAt, _updatedAt, ...patch } = content; saveMutation.mutate({ patch }); };

  if (loading || isLoading) return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", ...mono }}>Cargando panel...</div>;
  if (!user && !previewEditor) return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: "1.5rem", ...mono }}><form onSubmit={(event) => { event.preventDefault(); if (!accessCode.trim()) return; window.sessionStorage.setItem("blefaroplastia-preview-editor-code", accessCode.trim()); setPreviewEditor(true); window.location.reload(); }} style={{ width: "min(100%, 420px)", border: "1px solid oklch(0.82 0.005 60)", padding: "2rem", background: "white" }}><p style={{ fontSize: "0.62rem", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "1rem" }}>Edición de previsualización</p><h1 style={{ fontSize: "1.3rem", marginBottom: "0.8rem" }}>Accede al panel</h1><p style={{ fontSize: "0.72rem", lineHeight: 1.8, color: "oklch(0.42 0.01 60)", marginBottom: "1.2rem" }}>Introduce el código de edición facilitado para esta revisión. Este acceso solo funciona en la previsualización.</p><input aria-label="Código de edición" value={accessCode} onChange={(event) => setAccessCode(event.target.value)} style={{ ...fieldStyle, marginBottom: "1rem" }} /><button type="submit" style={{ ...mono, width: "100%", border: "none", background: "oklch(0.1 0.005 60)", color: "white", padding: "0.8rem", fontSize: "0.62rem", cursor: "pointer" }}>ABRIR PANEL</button></form></div>;
  if (user && user.role !== "admin" && !previewEditor) return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", ...mono }}>Acceso restringido.</div>;
  if (!content) return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", ...mono }}>No se ha podido cargar el contenido.</div>;

  const hero = content.hero ?? {}; const problem = content.problem ?? {}; const naturality = content.naturality ?? {}; const specialist = content.specialist ?? {}; const process = content.process ?? {}; const recovery = content.recovery ?? {}; const contact = content.contact ?? {}; const footer = content.footer ?? {}; const social = content.social ?? {}; const ui = content.ui ?? {}; const faqs = Array.isArray(content.faqs) ? content.faqs : [];
  return <div style={{ minHeight: "100vh", background: "oklch(0.975 0.005 60)", color: "oklch(0.1 0.005 60)" }}><header style={{ background: "oklch(0.1 0.005 60)", color: "white", padding: "1rem 1.5rem" }}><div style={{ maxWidth: "1100px", margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center" }}><strong style={{ ...mono, fontSize: "0.85rem", letterSpacing: "0.14em" }}>RHINO&amp;FACE · BLEFAROPLASTIA</strong><a href="/" target="_blank" rel="noopener noreferrer" style={{ ...mono, color: "white", fontSize: "0.6rem" }}>VER LANDING ↗</a></div></header><main style={{ maxWidth: "1100px", margin: "0 auto", padding: "2.5rem 1.5rem 7rem" }}>
    {previewEditor && <p style={{ ...mono, fontSize: "0.62rem", lineHeight: 1.8, maxWidth: "720px", padding: "0.8rem", background: "oklch(0.92 0.03 88)", border: "1px solid oklch(0.78 0.06 88)" }}>Acceso de edición activo para esta previsualización. No compartas el código de acceso.</p>}
    <p style={{ ...mono, fontSize: "0.72rem", color: "oklch(0.48 0.01 60)", lineHeight: 1.8, maxWidth: "720px" }}>Puedes editar todos los textos de la landing y subir una imagen individual para cada bloque de la galería. Las fotos se publican automáticamente al subirlas; los textos se guardan al pulsar el botón inferior.</p>
    <Group title="Imágenes"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "1rem" }}><ImageUpload label="Hero · imagen lateral" slot="hero" url={text(hero.imageUrl)} onPersist={(url) => ({ hero: { ...hero, imageUrl: url } })} /><ImageUpload label="Retrato del especialista" slot="specialist" url={text(specialist.imageUrl)} onPersist={(url) => ({ specialist: { ...specialist, imageUrl: url } })} />{gallery.map((item: any, index: number) => <ImageUpload key={index} label={item.label || `Imagen ${index + 1}`} slot={`gallery-${index + 1}` as ImageSlot} url={text(item.imageUrl)} onPersist={(url) => ({ cases: { ...(content.cases ?? {}), items: gallery.map((galleryItem: any, itemIndex: number) => itemIndex === index ? { ...galleryItem, imageUrl: url } : galleryItem) } })} />)}</div></Group>
    <Group title="Hero"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "2rem" }}><div><Field label="Etiqueta" value={text(hero.label)} onChange={(value) => setSection("hero", { ...hero, label: value })} /><Field label="Titular" value={text(hero.title)} onChange={(value) => setSection("hero", { ...hero, title: value })} multiline /><Field label="Descripción" value={text(hero.description)} onChange={(value) => setSection("hero", { ...hero, description: value })} multiline /></div><div><Field label="Texto alternativo de imagen" value={text(hero.imageAlt)} onChange={(value) => setSection("hero", { ...hero, imageAlt: value })} /><Field label="CTA principal" value={text(ui.ctaAssessment)} onChange={(value) => setSection("ui", { ...ui, ctaAssessment: value })} /><Field label="CTA WhatsApp" value={text(ui.ctaWhatsApp)} onChange={(value) => setSection("ui", { ...ui, ctaWhatsApp: value })} /></div></div></Group>
    <Group title="La mirada y tarjetas"><Field label="Etiqueta de sección" value={text(ui.sectionLook)} onChange={(value) => setSection("ui", { ...ui, sectionLook: value })} /><Field label="Título" value={text(problem.title)} onChange={(value) => setSection("problem", { ...problem, title: value })} multiline /><Field label="Introducción" value={text(problem.intro)} onChange={(value) => setSection("problem", { ...problem, intro: value })} multiline />{(problem.cards ?? []).map((card: any, index: number) => <div key={index} style={{ padding: "1rem", background: "white", marginBottom: "1rem" }}><Field label={`Tarjeta ${index + 1} · título`} value={text(card.label)} onChange={(value) => setCard(index, "label", value)} /><Field label={`Tarjeta ${index + 1} · texto`} value={text(card.text)} onChange={(value) => setCard(index, "text", value)} multiline /></div>)}</Group>
    <Group title="Naturalidad"><Field label="Etiqueta" value={text(ui.sectionNaturality)} onChange={(value) => setSection("ui", { ...ui, sectionNaturality: value })} /><Field label="Título" value={text(naturality.title)} onChange={(value) => setSection("naturality", { ...naturality, title: value })} multiline /><Field label="Subtítulo" value={text(naturality.subtitle)} onChange={(value) => setSection("naturality", { ...naturality, subtitle: value })} multiline />{(naturality.paragraphs ?? []).map((paragraph: string, index: number) => <Field key={index} label={`Párrafo ${index + 1}`} value={text(paragraph)} onChange={(value) => setSection("naturality", { ...naturality, paragraphs: naturality.paragraphs.map((item: string, itemIndex: number) => itemIndex === index ? value : item) })} multiline />)}</Group>
    <Group title="Galería"><Field label="Etiqueta" value={text(ui.sectionGallery)} onChange={(value) => setSection("ui", { ...ui, sectionGallery: value })} /><Field label="Título" value={text(content.cases?.title)} onChange={(value) => setSection("cases", { ...(content.cases ?? {}), title: value })} /><Field label="Subtítulo" value={text(content.cases?.subtitle)} onChange={(value) => setSection("cases", { ...(content.cases ?? {}), subtitle: value })} multiline /><Field label="Nota" value={text(content.cases?.note)} onChange={(value) => setSection("cases", { ...(content.cases ?? {}), note: value })} multiline />{gallery.map((item: any, index: number) => <div key={index} style={{ padding: "1rem", background: "white", marginBottom: "1rem" }}><Field label={`Imagen ${index + 1} · título`} value={text(item.label)} onChange={(value) => setGalleryItem(index, "label", value)} /><Field label={`Imagen ${index + 1} · texto alternativo`} value={text(item.imageAlt)} onChange={(value) => setGalleryItem(index, "imageAlt", value)} /></div>)}</Group>
    <Group title="Especialista"><Field label="Etiqueta" value={text(ui.sectionSpecialist)} onChange={(value) => setSection("ui", { ...ui, sectionSpecialist: value })} /><Field label="Nombre" value={text(specialist.name)} onChange={(value) => setSection("specialist", { ...specialist, name: value })} /><Field label="Especialidad" value={text(specialist.role)} onChange={(value) => setSection("specialist", { ...specialist, role: value })} />{(specialist.paragraphs ?? []).map((paragraph: string, index: number) => <Field key={index} label={`Párrafo ${index + 1}`} value={text(paragraph)} onChange={(value) => setSection("specialist", { ...specialist, paragraphs: specialist.paragraphs.map((item: string, itemIndex: number) => itemIndex === index ? value : item) })} multiline />)}</Group>
    <Group title="Proceso"><Field label="Etiqueta" value={text(ui.sectionProcess)} onChange={(value) => setSection("ui", { ...ui, sectionProcess: value })} /><Field label="Título" value={text(process.title)} onChange={(value) => setSection("process", { ...process, title: value })} />{(process.steps ?? []).map((step: any, index: number) => <div key={index} style={{ padding: "1rem", background: "white", marginBottom: "1rem" }}><Field label={`Paso ${index + 1} · número`} value={text(step.num)} onChange={(value) => setStep(index, "num", value)} /><Field label={`Paso ${index + 1} · título`} value={text(step.title)} onChange={(value) => setStep(index, "title", value)} /><Field label={`Paso ${index + 1} · texto`} value={text(step.text)} onChange={(value) => setStep(index, "text", value)} multiline /></div>)}</Group>
    <Group title="Recuperación"><Field label="Etiqueta" value={text(ui.sectionRecovery)} onChange={(value) => setSection("ui", { ...ui, sectionRecovery: value })} /><Field label="Título" value={text(recovery.title)} onChange={(value) => setSection("recovery", { ...recovery, title: value })} multiline />{(recovery.paragraphs ?? []).map((paragraph: string, index: number) => <Field key={index} label={`Párrafo ${index + 1}`} value={text(paragraph)} onChange={(value) => setSection("recovery", { ...recovery, paragraphs: recovery.paragraphs.map((item: string, itemIndex: number) => itemIndex === index ? value : item) })} multiline />)}</Group>
    <Group title="Preguntas frecuentes">{faqs.map((faq: any, index: number) => <div key={index} style={{ padding: "1rem", background: "white", marginBottom: "1rem" }}><Field label={`Pregunta ${index + 1}`} value={text(faq.question)} onChange={(value) => setContent({ ...content, faqs: faqs.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, question: value } : item) })} /><Field label={`Respuesta ${index + 1}`} value={text(faq.answer)} onChange={(value) => setContent({ ...content, faqs: faqs.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, answer: value } : item) })} multiline /></div>)}</Group>
    <Group title="Contacto, Instagram y footer"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "2rem" }}><div><Field label="Etiqueta de contacto" value={text(ui.sectionContact)} onChange={(value) => setSection("ui", { ...ui, sectionContact: value })} /><Field label="Título de contacto" value={text(contact.title)} onChange={(value) => setSection("contact", { ...contact, title: value })} multiline /><Field label="Descripción" value={text(contact.description)} onChange={(value) => setSection("contact", { ...contact, description: value })} multiline /><Field label="Teléfono" value={text(contact.phone)} onChange={(value) => setSection("contact", { ...contact, phone: value })} /><Field label="Link WhatsApp" value={text(contact.whatsappHref)} onChange={(value) => setSection("contact", { ...contact, whatsappHref: value })} /><Field label="Email" value={text(contact.email)} onChange={(value) => setSection("contact", { ...contact, email: value })} /></div><div><Field label="URL Instagram" value={text(social.instagramHref)} onChange={(value) => setSection("social", { ...social, instagramHref: value })} /><Field label="Texto botón Instagram" value={text(social.instagramLabel)} onChange={(value) => setSection("social", { ...social, instagramLabel: value })} /><Field label="Dirección footer" value={text(footer.address)} onChange={(value) => setSection("footer", { ...footer, address: value })} /><Field label="Navegación · La mirada" value={text(ui.navLook)} onChange={(value) => setSection("ui", { ...ui, navLook: value })} /><Field label="Navegación · Proceso" value={text(ui.navProcess)} onChange={(value) => setSection("ui", { ...ui, navProcess: value })} /><Field label="Navegación · Especialista" value={text(ui.navSpecialist)} onChange={(value) => setSection("ui", { ...ui, navSpecialist: value })} /><Field label="Navegación · Clínica" value={text(ui.navClinic)} onChange={(value) => setSection("ui", { ...ui, navClinic: value })} /></div></div></Group>
    <Group title="Textos de interfaz y formulario"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "2rem" }}><div><Field label="Etiqueta FAQ" value={text(ui.sectionFaq)} onChange={(value) => setSection("ui", { ...ui, sectionFaq: value })} /><Field label="Título FAQ" value={text(ui.faqTitle)} onChange={(value) => setSection("ui", { ...ui, faqTitle: value })} /><Field label="Texto WhatsApp directo" value={text(ui.directWhatsApp)} onChange={(value) => setSection("ui", { ...ui, directWhatsApp: value })} /><Field label="Etiqueta formulario · Nombre" value={text(ui.formName)} onChange={(value) => setSection("ui", { ...ui, formName: value })} /><Field label="Etiqueta formulario · Teléfono" value={text(ui.formPhone)} onChange={(value) => setSection("ui", { ...ui, formPhone: value })} /></div><div><Field label="Etiqueta formulario · Email" value={text(ui.formEmail)} onChange={(value) => setSection("ui", { ...ui, formEmail: value })} /><Field label="Etiqueta formulario · Mensaje" value={text(ui.formMessage)} onChange={(value) => setSection("ui", { ...ui, formMessage: value })} /><Field label="Texto de privacidad" value={text(ui.formPrivacy)} onChange={(value) => setSection("ui", { ...ui, formPrivacy: value })} multiline /><Field label="Botón de envío" value={text(ui.formSubmit)} onChange={(value) => setSection("ui", { ...ui, formSubmit: value })} /></div></div></Group>
    <button onClick={save} disabled={saveMutation.isPending} style={{ ...mono, position: "fixed", right: "1.5rem", bottom: "1.5rem", border: "none", background: "oklch(0.1 0.005 60)", color: "white", padding: "1rem 1.3rem", fontSize: "0.62rem", letterSpacing: "0.08em", textTransform: "uppercase", cursor: saveMutation.isPending ? "wait" : "pointer", boxShadow: "0 6px 24px rgba(0,0,0,.2)" }}>{saveMutation.isPending ? "Guardando..." : "Guardar cambios"}</button>
  </main></div>;
}
